import React, { useState } from 'react';
import { useAdmin } from '../../context/AdminContext';
import { StoredDiagnosticRecord } from '../../types';
import { 
  Cpu, 
  Search, 
  AlertTriangle, 
  CheckCircle2, 
  X, 
  MessageSquare, 
  Wrench, 
  MapPin, 
  Clock 
} from 'lucide-react';

export const AiDiagnosticsManagement: React.FC = () => {
  const { diagnostics, reviewDiagnosticRecord, assignTechnician, addBooking } = useAdmin();

  const [searchTerm, setSearchTerm] = useState('');
  const [severityFilter, setSeverityFilter] = useState<string>('all');
  const [selectedDiag, setSelectedDiag] = useState<StoredDiagnosticRecord | null>(null);
  const [managerNotes, setManagerNotes] = useState('');

  const filteredDiagnostics = diagnostics.filter(d => {
    const matchesSearch = 
      d.brand.toLowerCase().includes(searchTerm.toLowerCase()) ||
      d.applianceType.toLowerCase().includes(searchTerm.toLowerCase()) ||
      d.location.toLowerCase().includes(searchTerm.toLowerCase()) ||
      (d.errorCode && d.errorCode.toLowerCase().includes(searchTerm.toLowerCase()));
    
    const matchesSeverity = severityFilter === 'all' || d.severity === severityFilter;

    return matchesSearch && matchesSeverity;
  });

  const handleSaveReview = () => {
    if (selectedDiag && managerNotes) {
      reviewDiagnosticRecord(selectedDiag.id, managerNotes);
      setSelectedDiag(null);
    }
  };

  const handleCreateDispatchFromDiag = (d: StoredDiagnosticRecord) => {
    addBooking({
      fullName: `Diagnostic Lead (${d.brand})`,
      phone: '+254 700 000 000',
      email: 'lead@kenfoss.co.ke',
      location: d.location,
      serviceType: `${d.applianceType} Repair (${d.severity})`,
      date: new Date().toISOString().slice(0, 10),
      notes: `Generated from AI Diagnostic Submission: ${d.problemDescription}. AI Diagnosis: ${d.diagnosisSummary}`
    });
    alert('Emergency Service Booking dispatch created automatically from this AI Diagnostic submission!');
  };

  return (
    <div className="space-y-6">
      
      {/* Header */}
      <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6">
        <h1 className="text-xl font-black text-white flex items-center gap-2">
          <Cpu className="w-6 h-6 text-blue-400" />
          AI Diagnostics Submission & Telemetry Audit
        </h1>
        <p className="text-xs text-slate-400 mt-1">
          Review real-time equipment fault diagnostic requests generated by website visitors via Gemini AI.
        </p>
      </div>

      {/* Filters */}
      <div className="bg-slate-900 border border-slate-800 rounded-2xl p-4 flex flex-col md:flex-row items-center justify-between gap-4">
        <div className="relative w-full md:w-80">
          <Search className="absolute left-3.5 top-3 w-4 h-4 text-slate-500" />
          <input
            type="text"
            placeholder="Search equipment, brand, error code, location..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full pl-10 pr-4 py-2 bg-slate-950 border border-slate-800 rounded-xl text-xs text-white focus:outline-none focus:border-blue-500"
          />
        </div>

        <div className="flex flex-wrap gap-1.5 w-full md:w-auto">
          {['all', 'Low', 'Medium', 'High', 'Emergency Critical'].map(sev => (
            <button
              key={sev}
              onClick={() => setSeverityFilter(sev)}
              className={`px-3 py-1.5 rounded-xl text-xs font-bold transition-all cursor-pointer ${
                severityFilter === sev
                  ? 'bg-blue-600 text-white shadow-md'
                  : 'bg-slate-950 text-slate-400 hover:text-white border border-slate-800'
              }`}
            >
              {sev === 'all' ? 'All Severity Levels' : sev}
            </button>
          ))}
        </div>
      </div>

      {/* DIAGNOSTICS GRID */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {filteredDiagnostics.map(d => (
          <div key={d.id} className="bg-slate-900 border border-slate-800 rounded-3xl p-6 space-y-4 shadow-lg flex flex-col justify-between">
            <div className="space-y-3">
              
              <div className="flex items-start justify-between gap-2">
                <div>
                  <span className="text-[10px] font-mono text-slate-500 block uppercase font-bold">
                    Submitted {new Date(d.createdAt).toLocaleString()}
                  </span>
                  <h3 className="text-lg font-black text-white">{d.brand} {d.applianceType}</h3>
                </div>

                <span className={`px-2.5 py-1 rounded-full text-[10px] font-black uppercase shrink-0 ${
                  d.severity === 'Emergency Critical' ? 'bg-rose-500/20 text-rose-400 border border-rose-500/40' :
                  d.severity === 'High' ? 'bg-amber-500/20 text-amber-400 border border-amber-500/40' :
                  'bg-blue-500/20 text-blue-400 border border-blue-500/40'
                }`}>
                  {d.severity}
                </span>
              </div>

              {d.errorCode && (
                <div className="inline-block px-2.5 py-1 bg-slate-950 border border-slate-800 rounded-lg text-xs font-mono font-bold text-amber-400">
                  Fault Code: {d.errorCode}
                </div>
              )}

              <div className="p-3 bg-slate-950 rounded-2xl border border-slate-800 text-xs space-y-2">
                <div>
                  <span className="text-slate-500 font-extrabold uppercase text-[9px] block">Customer Symptom Description</span>
                  <p className="text-slate-300 italic">{d.problemDescription}</p>
                </div>

                <div className="pt-2 border-t border-slate-900">
                  <span className="text-blue-400 font-extrabold uppercase text-[9px] block">AI Engineer Diagnosis</span>
                  <p className="text-white font-medium">{d.diagnosisSummary}</p>
                </div>
              </div>

              <div className="flex items-center space-x-4 text-xs text-slate-400">
                <span className="flex items-center gap-1">
                  <MapPin className="w-3.5 h-3.5 text-slate-500" /> {d.location}
                </span>
                {d.equipmentAge && (
                  <span className="flex items-center gap-1">
                    <Clock className="w-3.5 h-3.5 text-slate-500" /> Age: {d.equipmentAge}
                  </span>
                )}
              </div>

              {d.reviewNotes && (
                <div className="p-3 bg-blue-950/30 border border-blue-900/40 rounded-xl text-xs space-y-0.5">
                  <span className="text-[10px] font-bold text-blue-400">Manager Review ({d.reviewedBy}):</span>
                  <p className="text-slate-200">{d.reviewNotes}</p>
                </div>
              )}

            </div>

            <div className="pt-3 border-t border-slate-800 flex items-center justify-between gap-2">
              <button
                onClick={() => {
                  setSelectedDiag(d);
                  setManagerNotes(d.reviewNotes || '');
                }}
                className="px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 font-bold text-xs rounded-xl cursor-pointer"
              >
                {d.reviewedBy ? 'Edit Review' : 'Add Manager Review'}
              </button>

              <button
                onClick={() => handleCreateDispatchFromDiag(d)}
                className="px-3 py-1.5 bg-[#0057B8] hover:bg-blue-600 text-white font-bold text-xs rounded-xl flex items-center gap-1 cursor-pointer"
              >
                <Wrench className="w-3.5 h-3.5" />
                <span>Create Dispatch</span>
              </button>
            </div>

          </div>
        ))}
      </div>

      {/* REVIEW MODAL */}
      {selectedDiag && (
        <div className="fixed inset-0 z-50 bg-slate-950/80 backdrop-blur-xs flex items-center justify-center p-4">
          <div className="bg-slate-900 border border-slate-800 text-slate-100 rounded-3xl max-w-md w-full p-6 space-y-4 shadow-2xl relative">
            <button
              onClick={() => setSelectedDiag(null)}
              className="absolute top-4 right-4 p-2 text-slate-400 hover:text-white"
            >
              <X className="w-5 h-5" />
            </button>

            <h3 className="text-lg font-bold text-white">Manager Diagnostic Audit</h3>
            <p className="text-xs text-slate-400">
              Add engineering follow-up notes or dispatch directives for <strong className="text-white">{selectedDiag.brand} {selectedDiag.applianceType}</strong>.
            </p>

            <div className="space-y-1">
              <label className="text-xs font-bold text-slate-300">Manager Follow-Up Notes</label>
              <textarea
                rows={3}
                value={managerNotes}
                onChange={(e) => setManagerNotes(e.target.value)}
                placeholder="e.g. Verified with client. Scheduled capacitor replacement with Tech. John."
                className="w-full p-3 bg-slate-950 border border-slate-800 rounded-xl text-xs text-white focus:outline-none focus:border-blue-500"
              />
            </div>

            <div className="flex justify-end space-x-2 pt-2 border-t border-slate-800">
              <button
                onClick={() => setSelectedDiag(null)}
                className="px-4 py-2 bg-slate-800 text-slate-300 font-bold text-xs rounded-xl cursor-pointer"
              >
                Cancel
              </button>
              <button
                onClick={handleSaveReview}
                className="px-4 py-2 bg-[#0057B8] hover:bg-blue-600 text-white font-bold text-xs rounded-xl cursor-pointer"
              >
                Save Review Notes
              </button>
            </div>
          </div>
        </div>
      )}

    </div>
  );
};
